# Data import and first inspection

Use venv to run this notebook
Run using: 
- **source venv/bin/activate** --> on linux

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
file_path = "../Data/cairo3a_poultry_dataset"
# data = pd.read_csv(file_path + '.csv.gz')
# data.to_parquet(file_path + ".parquet")
data = pd.read_parquet(file_path + ".parquet")

In [3]:
data.shape

(74354, 65)

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

In [5]:
data.head()

,flock_id,farm_id,house_id,cycle_number,date,age_days,breed,placement_count,house_type,governorate,stocking_density_per_m2,house_area_m2,doc_quality_score,doc_arrival_temp_c,hatchery_id,feed_batch_id,days_since_feed_delivery,current_flock_size,daily_deaths,daily_culls,cumulative_deaths,cumulative_culls,daily_mortality_pct,cumulative_mortality_pct,mortality_spike,avg_weight_g,weighing_done,hubbard_standard_weight_g,feed_consumed_kg,feed_per_bird_g,feed_phase,water_consumed_L,temp_inside_min_c,temp_inside_max_c,temp_inside_avg_c,target_temp_for_age_c,humidity_inside_pct,ammonia_ppm,co2_ppm,fan_runtime_hours,cooling_pad_status,power_outage_hours,temp_outside_avg_c,humidity_outside_pct,wind_speed_kmh,khamaseen_dust_storm,month,day_of_week,season,is_holiday,is_ramadan,vaccine_given,vaccine_route,scheduled_vaccine_today,days_since_last_vaccine,antibiotic_given,antibiotic_name,vitamin_supplement_given,litter_condition,worker_count,disease_event_id,suspected_disease,prev_cycle_mortality_pct,prev_cycle_fcr,house_total_cycles
0,FARM_001_H1_C01,FARM_001,FARM_001_H1,1,2023-02-10,1,Hubbard,29100,tunnel,Bahareya,19.4,1500,6.2,29.0,HTH_External_Fayoum,FB_001_C01_A,0,28662,393,45,393,45,1.3505,1.3505,1,43.0,1,45,401.3,14.0,starter,514.4,31.3,39.3,34.4,34.0,59.5,12.9,3255.0,3.1,off,0.0,17.3,37.7,21.8,0,2,4,winter,1,0,Mareks,injection,Mareks,0.0,0,None,1,moderate,1,None,None,NaN,NaN,1
1,FARM_001_H1_C01,FARM_001,FARM_001_H1,1,2023-02-11,2,Hubbard,29100,tunnel,Bahareya,19.4,1500,6.2,29.0,HTH_External_Fayoum,FB_001_C01_A,1,28432,200,30,593,75,0.6873,2.0378,1,NaN,0,57,503.2,17.7,starter,795.6,29.1,37.4,33.7,33.5,70.1,14.1,NaN,2.1,off,0.0,15.5,47.8,3.7,0,2,5,winter,0,0,None,None,None,1.0,0,None,1,None,3,None,None,NaN,NaN,1
2,FARM_001_H1_C01,FARM_001,FARM_001_H1,1,2023-02-12,3,Hubbard,29100,tunnel,Bahareya,19.4,1500,6.2,29.0,HTH_External_Fayoum,FB_001_C01_A,2,28179,216,37,809,112,0.7423,2.7801,1,NaN,0,72,588.9,20.9,starter,701.3,29.7,36.9,34.5,33.0,66.7,7.9,3027.0,5.9,off,0.0,18.2,40.4,2.5,0,2,6,winter,0,0,None,None,None,2.0,0,None,1,None,3,None,None,NaN,NaN,1
3,FARM_001_H1_C01,FARM_001,FARM_001_H1,1,2023-02-13,4,Hubbard,29100,tunnel,Bahareya,19.4,1500,6.2,29.0,HTH_External_Fayoum,FB_001_C01_A,3,28048,113,18,922,130,0.3883,3.1684,1,NaN,0,89,712.4,25.4,starter,1299.7,29.7,34.3,31.8,32.5,62.6,13.7,2839.0,3.5,off,0.0,13.8,44.8,5.5,0,2,0,winter,0,0,None,None,None,3.0,0,None,1,None,2,None,None,NaN,NaN,1
4,FARM_001_H1_C01,FARM_001,FARM_001_H1,1,2023-02-14,5,Hubbard,29100,tunnel,Bahareya,19.4,1500,6.2,29.0,HTH_External_Fayoum,FB_001_C01_A,1,27934,91,23,1013,153,0.3127,3.4811,1,NaN,0,109,812.9,29.1,starter,1550.8,27.7,35.1,31.2,32.0,58.9,20.2,NaN,3.0,off,0.0,15.7,43.8,1.0,0,2,1,winter,0,0,None,None,None,4.0,0,None,1,None,3,None,None,NaN,NaN,1

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 74354 entries, 0 to 74353
Data columns (total 65 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   flock_id                   74354 non-null  object
 1   farm_id                    74354 non-null  object
 2   house_id                   74354 non-null  object
 3   cycle_number               74354 non-null  int64
 4   date                       74354 non-null  object
 5   age_days                   74354 non-null  int64
 6   breed                      74354 non-null  object
 7   placement_count            74354 non-null  int64
 8   house_type                 74354 non-null  object
 9   governorate                74354 non-null  object
 10  stocking_density_per_m2    74354 non-null  float64
 11  house_area_m2              74354 non-null  int64
 12  doc_quality_score          74354 non-null  float64
 13  doc_arrival_temp_c         74354 non-null  float64
 14  hatchery_id                74354 non-null  object
 15  feed_batch_id              74354 non-null  object
 16  days_since_feed_delivery   74354 non-null  int64
 17  current_flock_size         74354 non-null  int64
 18  daily_deaths               74354 non-null  int64
 19  daily_culls                74354 non-null  int64
 20  cumulative_deaths          74354 non-null  int64
 21  cumulative_culls           74354 non-null  int64
 22  daily_mortality_pct        74354 non-null  float64
 23  cumulative_mortality_pct   74354 non-null  float64
 24  mortality_spike            74354 non-null  int64
 25  avg_weight_g               12705 non-null  float64
 26  weighing_done              74354 non-null  int64
 27  hubbard_standard_weight_g  74354 non-null  int64
 28  feed_consumed_kg           73186 non-null  float64
 29  feed_per_bird_g            73186 non-null  float64
 30  feed_phase                 74354 non-null  object
 31  water_consumed_L           71739 non-null  float64
 32  temp_inside_min_c          74354 non-null  float64
 33  temp_inside_max_c          74354 non-null  float64
 34  temp_inside_avg_c          74354 non-null  float64
 35  target_temp_for_age_c      74354 non-null  float64
 36  humidity_inside_pct        74354 non-null  float64
 37  ammonia_ppm                32047 non-null  float64
 38  co2_ppm                    9677 non-null   float64
 39  fan_runtime_hours          52967 non-null  float64
 40  cooling_pad_status         52967 non-null  object
 41  power_outage_hours         74354 non-null  float64
 42  temp_outside_avg_c         74354 non-null  float64
 43  humidity_outside_pct       74354 non-null  float64
 44  wind_speed_kmh             74354 non-null  float64
 45  khamaseen_dust_storm       74354 non-null  int64
 46  month                      74354 non-null  int64
 47  day_of_week                74354 non-null  int64
 48  season                     74354 non-null  object
 49  is_holiday                 74354 non-null  int64
 50  is_ramadan                 74354 non-null  int64
 51  vaccine_given              9055 non-null   object
 52  vaccine_route              9055 non-null   object
 53  scheduled_vaccine_today    9525 non-null   object
 54  days_since_last_vaccine    73153 non-null  float64
 55  antibiotic_given           74354 non-null  int64
 56  antibiotic_name            6714 non-null   object
 57  vitamin_supplement_given   74354 non-null  int64
 58  litter_condition           13335 non-null  object
 59  worker_count               74354 non-null  int64
 60  disease_event_id           6859 non-null   object
 61  suspected_disease          6859 non-null   object
 62  prev_cycle_mortality_pct   68515 non-null  float64
 63  prev_cycle_fcr             67764 non-null  float64
 64  house_total_cycles         74354 non-null  int64
dtypes: float64(24), int64(22), object(19)
memory usage: 36.9+ MB

In [7]:
data.isnull().sum().sort_values(ascending=False).head(18).to_frame()

                              0
antibiotic_name           67640
suspected_disease         67495
disease_event_id          67495
vaccine_given             65299
vaccine_route             65299
scheduled_vaccine_today   64829
co2_ppm                   64677
avg_weight_g              61649
litter_condition          61019
ammonia_ppm               42307
cooling_pad_status        21387
fan_runtime_hours         21387
prev_cycle_fcr             6590
prev_cycle_mortality_pct   5839
water_consumed_L           2615
days_since_last_vaccine    1201
feed_per_bird_g            1168
feed_consumed_kg           1168

In [8]:
null_summary = pd.DataFrame({
    "null_count": data.isnull().sum(),
    "null_percent": (data.isnull().mean() * 100).round(2)
}).sort_values("null_percent", ascending=False).head(18)

null_summary

                          null_count  null_percent
antibiotic_name                67640         90.97
suspected_disease              67495         90.78
disease_event_id               67495         90.78
vaccine_given                  65299         87.82
vaccine_route                  65299         87.82
scheduled_vaccine_today        64829         87.19
co2_ppm                        64677         86.99
avg_weight_g                   61649         82.91
litter_condition               61019         82.07
ammonia_ppm                    42307         56.90
cooling_pad_status             21387         28.76
fan_runtime_hours              21387         28.76
prev_cycle_fcr                  6590          8.86
prev_cycle_mortality_pct        5839          7.85
water_consumed_L                2615          3.52
days_since_last_vaccine         1201          1.62
feed_per_bird_g                 1168          1.57
feed_consumed_kg                1168          1.57

In [11]:
data.duplicated().sum()

np.int64(0)

In [ ]:
# It's a messy data with 65+ features! So, I will divide and conqure!
# Slicing the dataset into different feature groups based on their nature and relevance to the problem at hand.
# This will help in better understanding the data and also in feature engineering and model building later on.


# Identity
identities = [
    "flock_id",
    "farm_id",
    "house_id",
    "cycle_number",
    "date",
    "age_days"
]


# Flock Metadata
flock_metadata = [
    "breed",
    "placement_count",
    "house_type",
    "governorate",
    "stocking_density_per_m2",
    "house_area_m2",
    "doc_quality_score",
    "doc_arrival_temp_c",
    "hatchery_id",
    "feed_batch_id",
    "days_since_feed_delivery",
    "current_flock_size",
    "house_total_cycles"
]


# Weight
weight_features = [
    "avg_weight_g",
    "weighing_done",
    "hubbard_standard_weight_g"
]


# Feed
feed_features = [
    "feed_consumed_kg",
    "feed_per_bird_g",
    "feed_phase"
]


# =========================
# Water
# =========================
water_features = [
    "water_consumed_L"
]


# =========================
# Inside Environment
# =========================
inside_environment = [
    "temp_inside_min_c",
    "temp_inside_max_c",
    "temp_inside_avg_c",
    "target_temp_for_age_c",
    "humidity_inside_pct",
    "ammonia_ppm",
    "co2_ppm",
    "fan_runtime_hours",
    "cooling_pad_status",
    "power_outage_hours"
]


# =========================
# Outside Environment
# =========================
outside_environment = [
    "temp_outside_avg_c",
    "humidity_outside_pct",
    "wind_speed_kmh",
    "khamaseen_dust_storm"
]


# =========================
# Calendar
# =========================
calendar_features = [
    "month",
    "day_of_week",
    "season",
    "is_holiday",
    "is_ramadan"
]


# =========================
# Health Events
# =========================
health_events = [
    "vaccine_given",
    "vaccine_route",
    "scheduled_vaccine_today",
    "days_since_last_vaccine",
    "antibiotic_given",
    "antibiotic_name",
    "vitamin_supplement_given",
    "litter_condition",
    "worker_count"
]


# =========================
# Disease Ground Truth (DO NOT USE AS FEATURES)
# =========================
disease_ground_truth = [
    "disease_event_id",
    "suspected_disease"
]


# =========================
# Historical (Previous Cycle)
# =========================
historical_features = [
    "prev_cycle_mortality_pct",
    "prev_cycle_fcr"
]



# =========================
# Targets
# =========================
targets = [
    "daily_deaths",
    "daily_culls",
    "cumulative_deaths",
    "cumulative_culls",
    "daily_mortality_pct",
    "cumulative_mortality_pct",
    "mortality_spike"
]